project:
  type: website

website:
  title: "Sam Vaughan"
  favicon: "Images/icons/favicon-32x32.png"
  navbar:
    left:
      - research.qmd
      - writing.qmd
      - text: CV
        url: "CV.pdf"
      - icon: github
        href: https://github.com/samvaughan



format:
  html:
    theme: journal
    css: styles.css
    code-fold: show
    code-tools: true



